package billing

import (
	"encoding/json"
	"errors"
	"fmt"
	"math"
	"unicode"
	"unicode/utf8"

	"FrostAgent/internal/core"
)

var (
	ErrUnsupportedContentType = errors.New("unsupported chat message content type")
	ErrNilMessage             = errors.New("chat message is nil")
)

const (
	// Standard ChatML framing overheads
	MessageOverheadTokens = 4 // <|im_start|>role\n ... <|im_end|>\n
	PrimingOverheadTokens = 3 // <|im_start|>assistant<|im_sep|>
	ToolOverheadTokens    = 10
	DefaultImageTokens    = 1000 // Standard token estimate for image content
)

// EstimateTextTokens provides a local, fast token count estimation
// for multi-lingual text (Chinese, English, code, symbols).
func EstimateTextTokens(text string) int {
	if text == "" {
		return 0
	}

	var (
		cjkCount   int
		wordCount  int
		otherRunes int
		inWord     bool
	)

	for _, r := range text {
		if isCJK(r) {
			cjkCount++
			inWord = false
		} else if unicode.IsLetter(r) || unicode.IsDigit(r) {
			if !inWord {
				wordCount++
				inWord = true
			}
		} else if unicode.IsSpace(r) {
			inWord = false
		} else {
			// Punctuation, symbols, emojis
			otherRunes++
			inWord = false
		}
	}

	// Heuristic weights based on BPE tokenizers (cl100k_base / DeepSeek tokenizer):
	// - Chinese / CJK characters: ~1.2 tokens per character
	// - English words: ~1.3 tokens per word
	// - Punctuation / symbols: ~1 token per symbol
	estimated := float64(cjkCount)*1.2 + float64(wordCount)*1.3 + float64(otherRunes)*1.0

	// Byte-length sanity floor: at least ~1 token per 4 bytes
	byteFloor := float64(len(text)) / 4.0
	if byteFloor > estimated {
		estimated = byteFloor
	}

	result := int(math.Ceil(estimated))
	if result < 1 && len(text) > 0 {
		return 1
	}
	return result
}

func isCJK(r rune) bool {
	return (r >= 0x4E00 && r <= 0x9FFF) || // CJK Unified Ideographs
		(r >= 0x3400 && r <= 0x4DBF) || // CJK Unified Ideographs Extension A
		(r >= 0x20000 && r <= 0x2A6DF) || // CJK Unified Ideographs Extension B
		(r >= 0xF900 && r <= 0xFAFF) || // CJK Compatibility Ideographs
		(r >= 0x3040 && r <= 0x309F) || // Hiragana
		(r >= 0x30A0 && r <= 0x30FF) || // Katakana
		(r >= 0xAC00 && r <= 0xD7AF) // Hangul Syllables
}

// EstimateMessageTokens estimates token count for a single ChatMessage.
// Fails closed if content type is unsupported.
func EstimateMessageTokens(msg core.ChatMessage) (int, error) {
	total := MessageOverheadTokens

	switch content := msg.Content.(type) {
	case nil:
		// Message with no text content (e.g. tool call message only)
	case string:
		total += EstimateTextTokens(content)
	case []core.ContentPart:
		for _, part := range content {
			switch part.Type {
			case "text":
				total += EstimateTextTokens(part.Text)
			case "image_url":
				total += DefaultImageTokens
			default:
				total += EstimateTextTokens(part.Text)
			}
		}
	default:
		return 0, fmt.Errorf("%w: %T", ErrUnsupportedContentType, msg.Content)
	}

	// Account for tool calls generated by assistant
	for _, tc := range msg.ToolCalls {
		total += 4 // tool call framing
		total += EstimateTextTokens(tc.Function.Name)
		total += EstimateTextTokens(tc.Function.Arguments)
	}

	return total, nil
}

// EstimateMessagesTokens calculates estimated prompt tokens for a slice of messages and tool definitions.
func EstimateMessagesTokens(msgs []core.ChatMessage, tools []core.Tool) (int, error) {
	total := PrimingOverheadTokens

	for i, msg := range msgs {
		count, err := EstimateMessageTokens(msg)
		if err != nil {
			return 0, fmt.Errorf("message %d: %w", i, err)
		}
		total += count
	}

	for _, tool := range tools {
		total += ToolOverheadTokens
		total += EstimateTextTokens(tool.Name)
		total += EstimateTextTokens(tool.Description)
		if tool.Parameters != nil {
			paramJSON, err := json.Marshal(tool.Parameters)
			if err == nil {
				total += EstimateTextTokens(string(paramJSON))
			}
		}
	}

	return total, nil
}

// EstimateReservationAmount computes the minor-unit snowflake amount to reserve
// before calling the model, incorporating a safety multiplier on prompt tokens
// and reserving for max output tokens.
func EstimateReservationAmount(
	model string,
	msgs []core.ChatMessage,
	tools []core.Tool,
	maxOutputTokens int,
	safetyMultiplier float64,
) (int64, error) {
	promptTokens, err := EstimateMessagesTokens(msgs, tools)
	if err != nil {
		return 0, fmt.Errorf("estimate prompt tokens: %w", err)
	}

	if safetyMultiplier <= 0 {
		safetyMultiplier = 1.2
	}
	if maxOutputTokens <= 0 {
		maxOutputTokens = 2048
	}

	adjustedPrompt := int(math.Ceil(float64(promptTokens) * safetyMultiplier))
	amountMinor := CalculateCost(model, adjustedPrompt, maxOutputTokens)

	// Ensure at least 1 minor unit if pricing is non-zero
	price, _ := GetPrice(model)
	if amountMinor == 0 && (price.PromptPricePerMillion > 0 || price.CompletionPricePerMillion > 0) && utf8.RuneCountInString(model) > 0 {
		amountMinor = 1
	}

	return amountMinor, nil
}
